### PR TITLE
Updated tutorial documentation. I have divided the slide set in two, …

### PR DESCRIPTION
**Pull request by lvanfretti**
…one for the homework and one for the hands-on-examples.

I have added examples of using OMNotebook for Example 1 and Example 2.
Interactive analysis, parametric sweep and linearisation are now explained using OMNotebook. It is more “beginner friendly” for the case of linearisation.

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
Does this fix the typo mentioned in #111 ?

**Comment by lvanfretti** [comment]
I don't understand your last comment.

Yes, it fixes #111

Students pointed out other mistakes yesterday, I'm fixing the slides and will commit that also.

**Comment by lvanfretti** [comment]
@MaximeBaudette do you know how to convert from String to Real matrix?
I think is rather silly we have to do copy paste, but I couldn't find a specific conversion command in the scripting api: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html

**Comment by MaximeBaudette** [comment]
@lvanfretti 
You can keep this PR open and continue pushing to your branch, the PR will automatically be updated to reflect the latest commits. 

As to the string to matrix, I remember I tried to find a better solution but didn't. 

For my comment you can ignore it, it's fine.

**Comment by lvanfretti** [comment]
@MaximeBaudette sorry I closed it again, I am still making a lot of mistakes using Github, :-(

**Pull request merged**
