### PR TITLE
Removing DTU and Eurostag models.

### PR DESCRIPTION
**Pull request by tinrabuzin**

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
@tinrabuzin 
You removed the sensor package. The PwVoltageCurrent sensor is used in Controls.PSSE.ES.ESST4B

**Comment by tinrabuzin** [comment]
@MaximeBaudette I did it intentionally. I will reimplement ESST4B without the sensor. I think that's the only component that uses sensors.

**Comment by NiDingRte** [comment]
Hello,
I am working on the eurostag components in the ipsl package. I would like to know the reason why you have removed these components out of the OpenIPSL package? The OpenIPSL is not supposed to be an enhanced version of IPSL package?

Thx for your answer,
Regards,

**Comment by MaximeBaudette** [comment]
Hello @NiDingRte 

One of the main reasons for us removing most Eurostag models from the package is that those were not built like the other ones, mostly the dynamic models didn't include the initialization like the other models, but relied on a separate init model. 
Also as we tried to harmonize the models throughout the library with common interfaces, our colleagues in charge of the Eurostag models were reluctant to do so... So in the end there was a certain harmonization gap between the rest of the library and the Eurostag models, leading to our decision to drop those models in this fork. 

The intention for the OpenIPSL package, as I see it, is to propose a harmonized package, we are not there yet, but we have made substantial modifications already. It is not necessarily a better - or enhanced - package, mostly a more harmonized one. And also we are making effort to change it toward a more Modelica-like approach. 

Best regards,

**Pull request merged**
