### PR TITLE
Adds the units MW and Mvar to the dynamic bus display.

### PR DESCRIPTION
**Pull request by dietmarw**

### CODE REVIEW

**Comment by dietmarw** [comment]
the official unit of the reactive power is `var` not `VAr` :-P

Quote: 
> For reactive power Q, it was decided to introduce the letter “r”. Even if the unit of reactive power is consistent with VA, the International Electrotechnical Commission (IEC) proposed the symbol “var” (with small letters).

**Comment by dietmarw** [comment]
Also check IEC 60027-1 if you don't believe me.

**Comment by MaximeBaudette** [comment]
I swear I was taught `VAr` ... Good to learn new things everyday though ;-)
You can merge your PR !

**Comment by dietmarw** [comment]
So was I ... :frowning:

**Comment by MaximeBaudette** [comment]
Damn teachers who did not read their IEC standards  :astonished:

**Comment by tinrabuzin** [comment]
@MaximeBaudette I wanted to read one today. They're expensive...

**Comment by dietmarw** [comment]
They are. We need pirateIEC.

**Pull request merged**
