### PR TITLE
Update tutorial package

### PR DESCRIPTION
**Pull request by MaximeBaudette**
Fixing some errors in the presentation and modelica files

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
Ping @tinrabuzin 
Could you just validate this one so the participants to the tutorial got the right source code?

**Comment by lvanfretti** [comment]
@tinrabuzin hi! Could you check this?
I have to give the tutorial tomorrow.

**Comment by tinrabuzin** [comment]
@MaximeBaudette @lvanfretti 
Doing it right now...

**Comment by lvanfretti** [comment]
Thank you very much @tinrabuzin !!!

**Pull request merged**
