### PR TITLE
Add default prefixes definition for SystemBase

### PR DESCRIPTION
**Pull request by dietmarw**
This saves also one step in the tutorial ;-)

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
Hi @dietmarw, I noticed that when using Dymola, the prefix was automatically added, but not in OM. Would your modification solve this issue?

**Comment by dietmarw** [comment]
Yes that is exactly the purpose of it. I think I've also tested this already on OM. I will verify this on Monday but adding this does not harm anyway since it really should be present.

**Comment by dietmarw** [comment]
OK so OM respects the `defaultComponentPrefixes` annotation. So it does work there too.

**Comment by MaximeBaudette** [comment]
@dietmarw 
There is an issue with clahub :-( 
Any idea as to why? 
BTW, I was reading recently that Github updated its Terms of Use and that now by default a PR would by default transfer the copyright to the repository, so I guess maybe we could give up on ClaHub?

**Comment by dietmarw** [comment]
Yes I saw that with clahub too and am not sure what it is and how to resolve. 

As for clahub and the new (actually old) TOS as long as you want OpenIPSL stay under the current license clahub would not be necessary. It becomes (probably) an issue should you want to re-licence under a new licence.

**Comment by MaximeBaudette** [comment]
@dietmarw Should I just remove clahub then, it really seems to be stuck somewhere in the process?
I'll unlock the "mandatory" status check for now and merge the PR.

**Pull request merged**
